# Generated by Django 2.1.1 on 2018-10-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Game name', max_length=100, null=True, verbose_name='Name')),
                ('languages_game', models.CharField(help_text='Language of the game', max_length=150, null=True, verbose_name='Languages')),
                ('genres', models.CharField(help_text='Name of the Game Genre', max_length=50, null=True, verbose_name='Game Genre')),
            ],
            options={
                'verbose_name': 'Game Data',
                'verbose_name_plural': 'Games Data',
            },
        ),
        migrations.CreateModel(
            name='InfoSteam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positive_reviews_steam', models.IntegerField(help_text='Number of positive reviews at Steam', null=True, verbose_name='Steam Positive Reviews')),
                ('negative_reviews_steam', models.IntegerField(help_text='Number of negative reviews at Steam', null=True, verbose_name='Steam Negative Reviews')),
                ('owners', models.IntegerField(help_text='Name of the owners', null=True, verbose_name='Steam Owners')),
                ('average_forever', models.IntegerField(help_text='Average forever of the game', null=True, verbose_name='Average Played Time')),
                ('average_2weeks', models.IntegerField(help_text='Average Played Time 2 weeks of the game', null=True, verbose_name='Average Played Time 2 weeks')),
                ('price', models.IntegerField(help_text='Price of the game', null=True, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importdata.Game')),
            ],
            options={
                'verbose_name': 'Steam Data',
                'verbose_name_plural': 'Steam Data',
            },
        ),
        migrations.CreateModel(
            name='InfoTwitch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewer_count', models.IntegerField(help_text='Number of views in stream', null=True, verbose_name='Twitch Game streams Viewer count')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importdata.Game')),
            ],
            options={
                'verbose_name': 'Twitch Data',
                'verbose_name_plural': 'Twitch Data',
            },
        ),
        migrations.CreateModel(
            name='InfoYoutube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count_videos', models.IntegerField(help_text='Number of videos found in youtube request', null=True, verbose_name='Youtube total videos number')),
                ('count_views', models.IntegerField(help_text='Number of views summed from youtube videos', null=True, verbose_name='Youtube total views')),
                ('count_likes', models.IntegerField(help_text='Number of likes summed from youtube videos', null=True, verbose_name='Youtube total likes')),
                ('count_dislikes', models.IntegerField(help_text='Number of dislikes summed from youtube videos', null=True, verbose_name='Youtube total dislikes')),
                ('count_comments', models.IntegerField(help_text='Number of comments summed from youtube videos', null=True, verbose_name='Youtube total comments count')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importdata.Game')),
            ],
            options={
                'verbose_name': 'Youtube Data',
                'verbose_name_plural': 'Youtube Data',
            },
        ),
        migrations.CreateModel(
            name='TwitchStream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_stream', models.CharField(help_text='Language of stream', max_length=100, null=True, verbose_name='Twitch stream Language')),
                ('started_at', models.CharField(help_text='Date when stream started', max_length=100, null=True, verbose_name='Twitch stream Started date')),
                ('type', models.CharField(help_text='Type of stream', max_length=100, null=True, verbose_name='Twitch stream Type')),
                ('stream_view_count', models.IntegerField(help_text='Number of stream view count', null=True, verbose_name='Stream view count')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importdata.Game')),
            ],
            options={
                'verbose_name': 'Stream Data',
                'verbose_name_plural': 'Streams Data',
            },
        ),
    ]
